/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AbsensiMahasiswa;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arddhana Zhafran
 */
public class AbsensiMain extends javax.swing.JFrame {

    /**
     * Creates new form AbsensiMain
     */
    
    
    //public DbCon conn = new DbCon();
    
    public AbsensiMain() {
        initComponents();
        selectData();
        //conn.getConnection();
        Mahasiswa mhs = new Mahasiswa();
        
        
    }
    
    public void selectData(){
        String kolom[]={"Nama Mahasiswa","Nama Dosen","Mata Kuliah","Nama Ruang","Waktu Absensi"};
        DefaultTableModel dtm=new DefaultTableModel(null, kolom);
        String SQL="SELECT tb_mahasiswa.nama_mahasiswa, tb_dosen.nama_dosen, tb_matakuliah.nama_matakuliah,tb_ruang.nama_ruang,tb_absensi.waktu_absensi"
                + " FROM tb_absensi "
                + "JOIN tb_mahasiswa ON tb_absensi.id_mahasiswa=tb_mahasiswa.id_mahasiswa "
                + "JOIN tb_dosen ON tb_absensi.id_dosen=tb_dosen.id_dosen "
                + "JOIN tb_matakuliah ON tb_absensi.id_matakuliah = tb_matakuliah.id_matakuliah "
                + "JOIN tb_ruang ON tb_absensi.id_ruang=tb_ruang.id_ruang "
                + " ORDER BY waktu_absensi DESC ";
        ResultSet rs = DbCon.executeQuery(SQL);
        try {
            while(rs.next()){
                String nama_mahasiswa=rs.getString(1);
                String nama_dosen=rs.getString(2);
                String nama_matakuliah=rs.getString(3);
                String nama_ruang=rs.getString(4);
                String waktu_absensi=rs.getString(5);
                String data[]={nama_mahasiswa,nama_dosen,nama_matakuliah,nama_ruang,waktu_absensi};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
        //Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbAbsen.setModel(dtm);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rgSatu = new javax.swing.JButton();
        rgDua = new javax.swing.JButton();
        rgTiga = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAbsen = new javax.swing.JTable();
        btRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));

        rgSatu.setText("Ruang 1");
        rgSatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgSatuActionPerformed(evt);
            }
        });

        rgDua.setText("Ruang 2");
        rgDua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgDuaActionPerformed(evt);
            }
        });

        rgTiga.setText("Ruang 3");

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel1.setText("Selamat Datang");

        jLabel2.setText("Silakan Pilih Ruan Di bawah ini");

        jLabel3.setText("Record Absensi");

        tbAbsen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Nama Mahasiswa", "Dosen", "Mata Kuliah", "Ruangan", "Waktu"
            }
        ));
        jScrollPane1.setViewportView(tbAbsen);

        btRefresh.setText("Refresh");
        btRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rgSatu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rgDua, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(btRefresh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(rgTiga, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rgDua, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rgTiga, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rgSatu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rgSatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgSatuActionPerformed
        new MahasiswaMain(1).setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_rgSatuActionPerformed

    private void btRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshActionPerformed
        selectData();
    }//GEN-LAST:event_btRefreshActionPerformed

    private void rgDuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgDuaActionPerformed
        new MahasiswaMain(2).setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_rgDuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbsensiMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbsensiMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbsensiMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbsensiMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbsensiMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rgDua;
    private javax.swing.JButton rgSatu;
    private javax.swing.JButton rgTiga;
    private javax.swing.JTable tbAbsen;
    // End of variables declaration//GEN-END:variables
}
