/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AbsensiMahasiswa;

import javax.swing.JOptionPane;

/**
 *
 * @author Arddhana Zhafran
 */
public class MahasiswaMain extends javax.swing.JFrame {

    /**
     * Creates new form MahasiswaMain
     */
    Absensi ab = new Absensi();
    Ruang rg = new Ruang();
    Mahasiswa mhs = new Mahasiswa();
    int ruang;
    public MahasiswaMain(int id_ruang) {
        initComponents();
        labelRuang.setText("Ruang " + id_ruang);
        labelNamaRuang.setText("Kelas " + rg.get_nama_ruang_by_id(id_ruang));
        ruang = id_ruang;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        labelRuang = new javax.swing.JLabel();
        labelNamaRuang = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txNim = new javax.swing.JTextField();
        btCheck = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelRuang1 = new javax.swing.JLabel();
        labelRuang2 = new javax.swing.JLabel();
        labelRuang3 = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelKelas = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        btAbsen = new javax.swing.JButton();
        btBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelRuang.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        labelRuang.setText("Ruang x");

        labelNamaRuang.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        labelNamaRuang.setText("KUx.x.x");

        jLabel1.setText("Masukkan Username");

        txNim.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btCheck.setText("Check");
        btCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCheckActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelRuang1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        labelRuang1.setText("Nama");

        labelRuang2.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        labelRuang2.setText("Kelas");

        labelRuang3.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        labelRuang3.setText("Nim");

        labelNama.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N

        labelKelas.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N

        labelUsername.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRuang1)
                    .addComponent(labelRuang2)
                    .addComponent(labelRuang3))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUsername)
                    .addComponent(labelKelas)
                    .addComponent(labelNama))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRuang1)
                    .addComponent(labelNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRuang2)
                    .addComponent(labelKelas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRuang3)
                    .addComponent(labelUsername))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        btAbsen.setText("Absen");
        btAbsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbsenActionPerformed(evt);
            }
        });

        btBack.setText("Back");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(labelRuang)
                                .addGap(374, 374, 374)
                                .addComponent(btBack))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(labelNamaRuang))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txNim, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(labelRuang))
                    .addComponent(btBack))
                .addGap(6, 6, 6)
                .addComponent(labelNamaRuang)
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCheckActionPerformed
        
        mhs.cek_data(txNim.getText());
        mhs.cek_matakuliah_mahasiswa(txNim.getText(), ruang);
        if(mhs.cek == true){
            if(mhs.tes == true ){
                String nim = txNim.getText();
                mhs.get_data_mahasiswa(nim);
                labelNama.setText(mhs.nama_mahasiswa);
                labelUsername.setText(mhs.nim_mahasiswa);
                labelKelas.setText(mhs.kelas_mahasiswa);
            }else{
                JOptionPane.showMessageDialog(null, "Mahasiswa tidak terdaftar matakuliah pada ruangan ini");
            }
        }else{
            JOptionPane.showMessageDialog(null, "DATA TIDAK ADA");
        }
        if(!labelNama.getText().isEmpty()){
            txNim.disable();
        }
        
    }//GEN-LAST:event_btCheckActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        new AbsensiMain().setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_btBackActionPerformed

    private void btAbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbsenActionPerformed
        Absensi ab = new Absensi();
        MataKuliah matkul = new MataKuliah();
        matkul.get_jadwal_kuliah(ruang);
        
        mhs.cek_jam_kuliah(txNim.getText(), ruang);
        if(mhs.status_jam == true){
            ab.add_absensi(mhs.id_mahasiswa, mhs.id_dosen, ruang, mhs.id_matakuliah);
            if(ab.cek == true){
                new AbsensiMain().setVisible(rootPaneCheckingEnabled);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null,"Gagal Menyimpan");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Belum saatnya absen");
        }
        
    }//GEN-LAST:event_btAbsenActionPerformed

    /**
     * @param args the command line arguments
     */;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MahasiswaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MahasiswaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MahasiswaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MahasiswaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbsensiMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbsen;
    private javax.swing.JButton btBack;
    private javax.swing.JButton btCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelKelas;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNamaRuang;
    private javax.swing.JLabel labelRuang;
    private javax.swing.JLabel labelRuang1;
    private javax.swing.JLabel labelRuang2;
    private javax.swing.JLabel labelRuang3;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JTextField txNim;
    // End of variables declaration//GEN-END:variables
}
